version: "3.8"
services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: db
      DATABASE_PORT: 3306
    ports:
      - "8000:8000"

  product_service:
    build:
      context: ./product_service
    container_name: product_service
    ports:
      - "8001:8001"
   
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  

    depends_on:
      - user_service
      - product_service

