version: "3.8"

services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_HOST=db
    #   - DATABASE_PORT=5432
    #   - DATABASE_NAME=user_db
    #   - DATABASE_USER=user
    #   - DATABASE_PASSWORD=pass
    #   - REDIS_HOST=redis
    # # depends_on:
    #   - db
    #   - redis

  product_service:
    build:
      context: ./product_service
    container_name: product_service
    ports:
      - "8001:8001"
    # environment:
    #   - DATABASE_HOST=db
    #   - DATABASE_PORT=5432
    #   - DATABASE_NAME=product_db
    #   - DATABASE_USER=user
    #   - DATABASE_PASSWORD=pass
    #   - REDIS_HOST=redis
    # # depends_on:
    #   - db
    #   - redis

#   db:
#     image: postgres:13
#     container_name: postgres
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: pass
#       POSTGRES_DB: main_db
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:alpine
#     container_name: redis
#     ports:
#       - "6379:6379"

# volumes:
#   postgres_data:
