name: Build, Test, and Deploy Services

on:
  workflow_dispatch: # Allow manual triggering from GitHub UI

  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_user_service_test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger user_service test
        run: |
          curl -X POST https://api.github.com/repos/manu042k/your-repo/actions/workflows/user_service.yml/dispatches \
          -d '{"ref":"main"}'

  trigger_product_service_test:
    runs-on: ubuntu-latest
    needs: trigger_user_service_test
    steps:
      - name: Trigger product_service test
        run: |
          curl -X POST https://api.github.com/repos/manu042k/your-repo/actions/workflows/product_service.yml/dispatches \
          -d '{"ref":"main"}'

  trigger_deploy:
    runs-on: ubuntu-latest
    needs: trigger_product_service_test
    steps:
      - name: Trigger deployment
        run: |
          curl -X POST https://api.github.com/repos/manu042k/your-repo/actions/workflows/deploy.yml/dispatches \
          -d '{"ref":"main"}'
