name: Build Product Service

on:
  workflow_run:
    workflows: ["Build, Test, and Deploy Services"]
    types:
      - completed

  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu image for the runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" # Set your required Python version

      - name: Install dependencies
        run: |
          cd product_service
          pip install -r requirements.txt  # Install dependencies for the product_service

      - name: Build Docker image 
        run: |
          cd product_service
          docker build -t product_service_image .  # Build a Docker image if needed
